### ISSUE TITLE
Cannot find module './jsonWebToken'

### ISSUE THREAD

**Issue by msukhotin** [jolocom/jolocom-lib#207]
1. Create a new npm project, then add a dependency: `npm install jolocom-lib --save`
2. Create index.js
```javascript
"use strict";
const JolocomLib = require("jolocom-lib").JolocomLib;
const identityManager = JolocomLib.identityManager.create(Buffer.from('abcd'));
```
3. Run it: `node index.js`. 

The output is:
```
Error: Cannot find module './jsonWebToken'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/max/projects/jolocom-test/node_modules/jolocom-lib/js/interactionFlows/JSONWebTokenParser.js:3:22)
```

Environment: ubuntu 18.04, node v8.10.0, npm 3.5.2

**Comment by katszwn** [comment]
Thanks for reporting! Currently none of us uses ubuntu so we were not aware of the issue.
