### ISSUE TITLE
yarn install fails because of sha3 / node 10+

### ISSUE THREAD

**Issue by lukas4k** [jolocom/jolocom-lib#247]
`yarn install` fails for on my environment for _jolocom-lib, smartwallet-app and demo-sso_ because sha3 does not compile. 

As I am not familiar with yarn, I assume its about my environment / sha3 related, however, just documenting the problem for now here as it may have sideffects (just a random assumption) for above products I am heaving a look these days.

My environment is
```
yarn 1.7.0
node v10.4.0
macOS Mojave, version: 10,14
What do I miss?
```

Current state

**jolocom-lib**
`npm install && npm test` # works

**smartwallet-app**
`npm install` # failed first, but installing node-pre-gyp helped.
adb is able to install app.

**demo-sso**
`npm install && yarn start` # worked for https://github.com/jolocom/demo-sso/commit/0d062d02d39e036447db849877171cc5b6930740

`yarn install` resolves in:

```
[4/4] 📃  Building fresh packages...
[1/10] ⡀ sha3
[2/10] ⡀ secp256k1
[3/10] ⡀ scrypt
[4/10] ⡀ keccak
error /Users/XYZ/smartwallet-app/node_modules/sha3: Command failed.
Exit code: 1
[Command: node-gyp rebuild
Arguments: 
Directory: /Users/XYZ/smartwallet-app/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.4.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/XYZ/smartwallet-app/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/XY/.node-gyp/10.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/XY/.node-gyp/10.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/XY/.node-gyp/10.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/XYZ/smartwallet-app/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]]

```
According to https://github.com/nodejs/node-gyp/issues/569 this seems not to be an issue (done in my environment):

```
[xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance]
```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/Cellar/node/10.4.0/bin/node" "/usr/local/Cellar/node/10.4.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/XYZ/smartwallet-app/node_modules/sha3
```

**Comment by lukas4k** [comment]
As side-effect of https://github.com/jolocom/smartwallet-app/issues/1165, this issue disappeared.

I won't have time for a better tracking down / reporting to sha3, however, you could think to inform users / devs which node version jolocom is supporting.
