### ISSUE TITLE
Use Object.defineProperties instead of Object.assign

### ISSUE THREAD

**Issue by katszwn** [jolocom/jolocom-lib#50]
### Description
In React Native using `Object.assign` is not allowed https://github.com/facebook/react-native/issues/5507
The error I was getting while running iOS app: 

> YellowBox.js:80 Possible Unhandled Promise Rejection (id: 0):
TypeError: One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant.
TypeError: One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant.
    at Function.Object.assign (webpack-internal:///./node_modules/haul/vendor/polyfills/Object.es6.js:55:7)
    at AuthenticationCredential.toJSON (webpack-internal:///./node_modules/jolocom-lib/js/ts/identity/authenticationCredential.js:33:23)
    at JSON.stringify (<anonymous>)
    at Identity.create (webpack-internal:///./node_modules/jolocom-lib/js/ts/identity/index.js:19:42)
    at Object.eval (webpack-internal:///./src/actions/registration/index.ts:64:42)
    at step (webpack-internal:///./node_modules/tslib/tslib.js:134:27)
    at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.js:115:57)
    at eval (webpack-internal:///./node_modules/tslib/tslib.js:108:75)
    at tryCallTwo (webpack-internal:///./node_modules/promise/setimmediate/core.js:45:5)
    at doResolve (webpack-internal:///./node_modules/promise/setimmediate/core.js:200:13)
    at new Promise (webpack-internal:///./node_modules/promise/setimmediate/core.js:66:3)
    at Object.__awaiter (webpack-internal:///./node_modules/tslib/tslib.js:104:16)
    at eval (webpack-internal:///./src/actions/registration/index.ts:53:16)
    at eval (webpack-internal:///./node_modules/redux-thunk/lib/index.js:11:18)
    at Object.generateAndEncryptKeyPairs (webpack-internal:///./src/ui/registration/containers/loading.tsx:35:73)
    at LoadingContainer.componentDidMount (webpack-internal:///./src/ui/registration/containers/loading.tsx:12:12)
    at commitLifeCycles (webpack-internal:///./node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:10592:11)
    at commitAllLifeCycles (webpack-internal:///./node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:11979:1)
    at Object.invokeGuardedCallback (webpack-internal:///./node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:39:6)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:221:25)
    at commitRoot (webpack-internal:///./node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:12116:1)
    at completeRoot (webpack-internal:///./node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:13087:30)

### TODO
- [ ] reproduce the error
- [ ] use `Object.defineProperties` instead

**Comment by Exulansis** [comment]
Sorted out.
